### ISSUE TITLE
Yet anther graphical glitch

### ISSUE THREAD

**Issue by unlink2** [luigitus/StrimBagZ#1]
I discovered this today while tapping on the games list and then immediately change to another view before it finishes loading this will happen sometimes:
![screenshot_2015-08-02-12-40-19](https://cloud.githubusercontent.com/assets/2109108/9027569/cba1bf1c-395a-11e5-83f8-a903809e85e7.png)
![screenshot_2015-08-02-12-40-03](https://cloud.githubusercontent.com/assets/2109108/9027571/d5d1ee44-395a-11e5-930e-a63a53c1629d.png)

Device: Nexus 5 on Android 5.1.1

**Comment by luigitus** [comment]
I got several reports on this, my best guess right now is that the fragments get not cleaned up for whatever reason, I'll look into that now
